TELang.lang = $.extend(TELang.lang, {
    StatusBar_Copyright: "&copy; 2019, Skyline Software Systems",
    StatusBar_East: "E",
    StatusBar_West: "W",
    StatusBar_North: "N",
    StatusBar_South: "S",
    StatusBar_MGRS: "MGRS",
    Meter: "Meter",
    meters: "meters",
    meters_short: "m",
    Km: "Km",
    km: "km",
    Feet: "Feet",
    feet: "feet",
    feet_short: "ft",
    Mile: "Mile",
    mile: "mile",
    pixels: 'pixels',
    UnsupportedLayers_Alert: "Some layers cannot be loaded. ${aTag} Click for more details ${closedATag}",
    UnsupportedLayers_Alert_List: "The following layers cannot be loaded:",
    Login_Layers_Alert: "Some additional layers may be available for the new login. ${aTag} Click here to refresh the layers list by reloading TerraExplorer for Web. ${closedATag} ",
    IE_Alert: "Some features may not work as expected in Internet Explorer 11.${brTag}It is recommended to use a different browser for full support.",
    Msg_LayerFromNonSecuredServer: "Layers from non-secured (HTTP) servers cannot be read by TerraExplorer for Web when running as a secured website (HTTPS).",
    Msg_CouldNotCreateLayer: "Could not create the requested layer",
    Menu_Menu: "Menu",
    Menu_Analyze: "Analyze",
    Menu_Time: "Time",
    Menu_Shadow: "Shadow",
    Menu_Layers: "Layers",
    Menu_Layers_Toolbox: "Layer: ${LayerName}",
    Menu_Load_Layers: "SkylineGlobe Layers",
    Menu_myDialogTool: "My Dialog Tool",
    Menu_myContainerTool: "My Container Tool",
    Menu_myDialogTool_Desc: "Hello From My Dialog Tool !",
    Menu_myContainerTool_Desc: "Hello From My Container Tool !",
    menuEntry_displayName_Navigation: "Navigate",
    menuEntry_displayName_Layers: "Layers",
    menuEntry_displayName_Analyze: "Analysis",
    menuEntry_displayName_Places: "Locations",
    Menu_Places: "Places",
    Menu_Underground: "Underground",
    Menu_Setting: "Settings",
    Menu_Analyze_Distance: "Distance",
    Menu_Analyze_Query: "Query",
    Menu_Analyze_Area: "Area",
    Menu_Analyze_Volume: "Volume",
    Menu_Analyze_Oblique_Viewer: "Oblique Viewer",
    Area_Result: "Horizontal Area Result",
    Menu_Analyze_Profile: "Profile",
    SearchBox_coordinates: "Coordinates:${newLine} ${longitude} (Lon), ${latitude} (Lat)",
    SearchBox_coordinates_MGRS: "Coordinates:${newLine} ${longitude} (Lon), ${latitude} (Lat) ${newLine2} ${MGRS} (MGRS)",
    Disabled_Layer: "Coordinate system not in Lat-Long WGS 84",
    Reason: "Reason" ,
    Video_Type_Not_Supported: '“Failed to load video. Only mp4, webm, and quicktime file formats are supported.”',
    non_LatLon_Layer: "Layers that are not in Lat-Long WGS 84 cannot be read by TerraExplorer for Web.",
    EditLayerTool_Classification_Label: "Apply Classification",
    EditLayerTool_AltitudeMethod_RelativeTo3DML : 'Relative To 3DML',
    edit_layers_label_text: "label text",
    Profile_Result: "Profile Result",
    measure_distance_Total_distance: "Total: ${adist}",
    measure_distance_aerial: "Total aerial distance: ${adist}",
    measure_distance_horizontal: "Total horizontal distance: ${hdist}",
    measure_distance_slope: "Slope (first-last): ${slope}°",
    measure_distance_elevation: "Elevation diff. (first-last): ${elevationDiff}",
    measure_distance_ground: "Total ground distance: ${gdist}",
    measure_area_horizontalArea: "Horizontal area: ${area}",
    measure_area_area: "Area: ${area}",
    measure_area_perimeter: "Perimeter: ${perimeter}",
    measure_volume_remove: "Removed Volume: ${removedVol}",
    measure_volume_added: "Added Volume: ${addedVol}",
    measure_area_ground: "Terrain surface: ${gsurface}",
    measure_square: "Square",
    measure_cubic: "cubic",
    Cancel: "Cancel",
    SettingsTool_EmptyFields: "One or more fields are empty..",
    DisplayName_ErrorMessage: "Error - Please Try Again",
    SettingsTool_UserPassIncorrect: 'The user name or password you entered is incorrect. Please try again.',
    SettingsTool_DeleteCookieProblem: "Problem - unable to delete cookie from server",
    connectToSG: "Connect",
    disconnectFromSG: "Disconnect",
    SettingsTool_disconnectMessage: "You are disconnected from SGS.",
    query_attributes_header: "Attributes",
    LayersTool_LoadLayersFromServer: "Load Layers",
    my_favorite_location: "My Location",  //TT #24155
    PlacesTool_AddFavorites: "Create Location", //TT #24155
    Distance_Result: "Distance Result",
    DistanceObj_DefaultName : "Distance #",
    VideoObj_DefaultName : "Video #",
    AreaObj_DefaultName: "Area #",
    VolObj_DefaultName: "Volume #",
    modifyTerrain_DefaultName : "Modify Terrain #",
    modifyB3dm_DefaultName : "Modify B3dm #",
    measure_distance_tooltip_delete: "Delete all points",
    measure_distance_tooltip_delete_last_point: "Delete last point",
    measure_distance_tooltip_ground_distance: "Calculate ground distance",
    measure_profile_tooltip_terrain_profile: "Calculate terrain profile",
    measure_area_tooltip_delete: "Delete all points",
    measure_area_tooltip_delete_last_point: "Delete last point",
    measure_area_tooltip_ground_area: "Calculate terrain surface area",
    measure_area_cannot_calculate_area: "The polygon that was created intersects itself and is invalid.\nPlease create a valid polygon.",
    measure_volume_tooltip_delete: "Delete all points",
    measure_volume_tooltip_delete_last_point: "Delete Last Point",
    measure_finish_drawing_tool: "Finish drawing",
	message_link_attribute: "Attributes Result",
	message_link_title: "Message Link",
    title_activity_places: "Places",
    places_favorites: "My Locations", //TT #24155
    places_locations: "Locations",
    places_presentations: "Presentations",
    Button_close: "Close",
    Button_save: "Save",
    AttrTable_Button_search: "Search",
    AttrTable_Button_undo: "Undo",
    AttrTable_Button_redo: "Redo",
    AttrTable_search_string: 'Search String',
    AttrTable_loading_wait: 'Loading. Please Wait...',
    AttrTable_save_changes: 'Some changes to attribute field values were not saved. Are you sure you want to continue with the search and lose these changes?',
    AttrTable_query_illegal: 'Syntax error: Use the Query Builder or type your own search string consisting of one or more conditions, each composed of an attribute, one of the following operators: ‘=’, ‘<>’, ‘>’, ‘>=’, ‘<’, ‘<=’, ‘Like’ and an attribute value. Multiple conditions are connected using AND & OR.',
    AttrTable_search_failed: 'Failed to retrieve features from server',
    AttrTable_display_first_results: 'Displaying first ${firstItemscount} items',
    AttrTable_display_results: 'Displaying ${itemscount} items',
    all: "All",
    open: "Open",
    view: "View",
    Query_Favorite_ToolTip: 'Add to My Locations', //TT #24155
    Query_FlyAround_ToolTip: 'Fly around location or object',
    Shadow_DateHour_ToolTIp: 'Select a date and hour',
    Contour_Lines_ToolTip: 'Display contour lines',
    Contour_Colors_ToolTip: 'Display contour colors',
    settings_contour_Dynamic : 'Contour Map : Dynamic Mode',
    settings_contour_Static : 'Contour Map : Static Mode',
    PresentationTool_Rewind_ToolTip:'Jump to previous step',
    PresentationTool_PlayPause_ToolTip: 'Play/Pause',
    PresentationTool_Forward_ToolTip: 'Jump to next step',
    PresentationTool_ListSteps_ToolTip: 'Open list of presentation steps',
    PresentationTool_PresentationCaption: "Presentation: ${presentationName}",
    analysis_query_explanation_text: "Click on the terrain or an object to query information about it.",
    analysis_area_explanation_text: "Click on the terrain to measure horizontal area.",
    analysis_distance_explanation_text: "Click on the terrain to measure distance.",
    analysis_profile_explanation_text: "Click on the terrain to measure terrain profile.",
    analysis_volume_explanation_text: "Click on the terrain to measure volume analysis.",
    anaylsis_time_explanation_text: "Use the slider and calendar to set the date and time.",
    analysis_oblique_explanation_text: "Click on a point on the ground to check what are the obliques that containing this point.<br> Forward looking cameras are in white and backward looking cameras are in yellow.",
    analysis_oblique_no_footprints_found: "No footprints were found at this location",
    context_menu_add_favorites: "Add to My Locations", ////TT #24155
    Edit_Feature_Layer_Style: "Edit Feature Layer Style",
    Attribute_Table_Title: "Attributes Table",
    edit_layer_icon_or_label: "Display Point As ",
    EditLayerTool_AltitudeMethod : 'Altitude Method', 
    EditLayerTool_AltitudeOffset: 'Altitude Offset',
    EditLayerTool_ClampToModel : 'Model',
    EditLayerTool_ClampToTerrain : 'Terrain',
    EditLayerTool_ClampTo : 'Clamp To',
    edit_layer_name: "Name",
    edit_layer_type: "Type",
    edit_layer_width: "Width",
    edit_layer_lineWidth: "Line Width",
    edit_layer_Opacity: "Opacity",
    edit_layer_color: "Color",
    edit_layer_outline_color: "Outline Color",
    edit_layer_Icon: "Icon URL",
    edit_layer_label_text: "Label Text",
    edit_favorite_name: "Name",
    edit_favorite_show_in_3d_view: "Show in 3D view",
    edit_favorite_icon: "Icon",
    edit_favorite_message: "Message",
    title_activity_favorites: "My Locations", ////TT #24155
    Alert_Message: "TerraExplorer Web",
    favorites_default_name: "My location",
    favorite_icon_star_red: "Red Star",
    favorite_icon_star_green: "Green Star",
    favorite_icon_star_purple: "Purple Star",
    favorite_icon_star_blue: "Blue Star",
    favorite_icon_star_yellow: "Yellow Star",
    FeaturePoint: "Feature Point",
    FeaturePolyline: "Feature Polyline",
    FeaturePolygon: "Feature Polygon",
    messageView_attr_name: "Attribute name",
    messageView_attr_value: "Attribute value",
    layers_default_name: "My layer",
    layers_sort_by_type: "Sort by Type",
    layers_sort_by_group: "Sort by Group",
    Calendar: "Calendar",
    layers_mesh_layers: "3D Layers",
    layers_cpt_layers: "Cloud Point Models",
    layers_feature_layers: "Feature Layers",
    layers_elevation_layers: "Elevation Layers",
    layers_raster_layers: "Raster Layers",
    layers_my_layers: "My Layers",
    layers_project_layers: "Project Layers",
    layers_viewshed_objects: "Viewshed",
    analysis_add_viewshed: "Viewshed",
    analysis_objects: "Objects",
    object_name: "Name:",
    Query_Result: "Query Result",
    title_activity_terrain_profile: "Terrain Profile",
    measure_terrain_profile_show_header: "Show",
    measure_terrain_profile_show_slopes: "Max Slopes",
    measure_terrain_profile_show_altitude: "Min/Max Altitude",
    measure_terrain_profile_show_waypoints: "Waypoints",
    measure_terrain_profile_tooltip_height: "Height",
    longitude: "Longitude",
    latitude: "Latitude",
    altitude: "Altitude",
    MAX_NUM_VIEWSHEDS_EXCEEDED: "The maximum number ${maxNumViewsheds} of viewsheds has been reached. One of the existing viewsheds must be deleted before a new one can be created.",
    area_Tooltip_Horizontal: "Horizontal Mode",
    area_Tooltip_3D_Plane: "3D Plane Mode",
    area_Horizontal_Mode: "Horizontal Mode",
    area_3D_Plane_Mode: "3D Plane Mode",
    viewshed_display_Name: "Name",
    viewshed_display_hFov: "Horizontal FOV",
    viewshed_display_vFov: "Vertical FOV",
    viewshed_display_Mode: "Mode",
    viewshed_display_Mode_Preview: "Preview",
    viewshed_display_Mode_Calculated: "Calculated",
    viewshed_display_properties: "3D Viewshed Properties",
    viewshed_display_X: "X",
    viewshed_display_Y: "Y",
    viewshed_display_Altitude: "Altitude",
    viewshed_display_AltitudeMethod: "Altitude Method",
    viewshed_display_newViewshedName: "Viewshed #",
    viewshed_altitude_method_sea: "Absolute",
    viewshed_altitude_method_ground: "Relative to terrain",
    viewshed_altitude_method_model: "Relative to 3DML",
    viewshed_process_loading: "Calculating Viewshed...",
    viewshed_retrieving_data: "Retrieving Viewshed Data...",
    viewshed_process_cancel: "Cancel",
    viewshed_display_distance: "Distance",
    Viewshed_Description_Text: "Ask Eylon for a descriptive text..",
    Viewshed_Tooltip_Delete: "Delete Viewshed",
    Viewshed_Tooltip_Properties: "Viewshed Properties",
    Viewshed_Tooltip_Move_Horizontal: "Move Horizontal",
    Viewshed_Tooltip_Move_Vertical: "Move Vertical",
    Viewshed_Tooltip_Calculate: "Calculate highest quality viewshed analysis",
    Viewshed_Calculate_href: "${aTag} Calculate ${closedATag}",
    Volume_Analysis_display_altitude_offset: "Altitude Offset",
    Volume_Analysis_display_AltitudeMethod: "Altitude Method",
    Volume_Analysis_display_Quality: "Quality",
    Volume_Analysis_display_properties: "Volume Analysis Properties",
    Volume_Analysis_altitude_method_absolute: "Absolute",
    Volume_Analysis_altitude_method_relative_to_terrain: "Relative to terrain",
    Volume_Analysis_altitude_method_model: "Relative to 3DML",
    Volume_Analysis_altitude_method_on_terrain: "On Terrain",
    Volume_Analysis_altitude_quality_low: "Low",
    Volume_Analysis_altitude_quality_medium: "Medium",
    Volume_Analysis_altitude_quality_high: "High",
    Volume_display_Name: "Name",
    Volume_Analysis_Tooltip_Claculate: "Calculate volume of object",
    Volume_Analysis_Tooltip_Properties: "Volume Analysis Properties",
    Volume_Analysis_Volume: "Volume: ",
    Volume_Analysis_Calculate: "Calculate",
    Volume_Analysis_Calculating: "Calculating...",
    Volume_Analysis_Calculated: "Calculated",
    query_latitude_pivot: "Latitude (pivot)",
    query_longitude_pivot: "Longitude (pivot)",
    query_altitude_pivot: "Altitude (pivot)",
    query_Name: "Name",
    query_ID: "ID",
    query_unknown: "Unknown",
    query_Address: "Address",
    query_LayerName: "Layer Name",
    query_FeatureName: "Feature Name",
    presentation_step: "Step",
    settings_color_scheme_header: "3D Map Color Adjustment:  ",
    settings_general_header: "General",
    settings_contour_header: "Contour Map:  ",
    settings_quality_resolution_scale_header: "Quality:  ",
    presentation_flyto: "fly to",
    presentation_wait: "wait",
    presentation_Flyto: "Fly to",
    presentation_Wait: "Wait",
    presentation_Wait_Seconds: "Wait ${numSeconds} seconds",
    presentation_caption: "caption",
    presentation_Caption: "Caption",
    presentation_ClearCaption: "Clear caption",
    presentation_Message: "Message",
    presentation_Play_Speed: "Set play speed:",
    Menu_Analyze_ContourMap: "Contour Map",
    Menu_Analyze_Slope: "Slope Map",
    Menu_Analyze_LineOfSight: "Line Of Sight",
    Menu_Analyze_Viewshed: "ViewshedTool",
    Menu_Navigate_TwoDMode: "2D",
    Menu_Navigate_TwoDNorthMode: "2D North",
    Menu_Navigate_ThreeDMode: "3D",
    Menu_Navigate_Rotate: "Fly Around",
    presentation_seconds: "seconds",
    title_activity_presentation: "Presentation Steps: ${presentationName}",
    title_activity_settings: "Settings",
    settings_URL: "Server Address",
    settings_User: "User",
    settings_Pass: "Password",
    settings_units: "Units:  ",
    settings_Open_Another_Project: "Open Another Project",
    settings_Scheme_Color_Bright: "Bright",
    settings_Scheme_Color_Cold: "Cold",
    settings_Scheme_Color_Warm: "Warm",
    settings_Scheme_Color_Natural: "Natural",
    settings_Quality_High: "High",
    settings_Quality_Medium: "Medium",
    settings_Quality_Low: "Low",
    settings_contour_colors: 'Colors',
    settings_contour_colors_lines: 'Colors & Lines',
    settings_units_meters: "Meters, km/h",
    settings_units_feet: "Feet, mph",
    settings_about: "About ",
    settings_showErrorsLog: "Show Errors",
    settings_online_help: "Online Help",
    title_settings_about: "About TerraExplorer for Web",
    TerraExplorer: "TerraExplorer",
    settings_SGS_Header: "SkylineGlobe Server",
    settings_Analysis_Header: "Analysis",
    settings_Objects_Header: "Objects",
    settings_Objects_Save: "Save Objects",
    settings_Objects_show_and_Save: "Save on this computer",
    settings_Objects_show_witout_saving: "Save until exit page",
    settings_Objects_no_show_save: "Delete when close tool",
    settings_about_version_abr: "v",
    settings_License_Agreement: "License Agreement",
    settings_TerraExplorer_For_Web_License: "TerraExplorer For Web License",
    settings_TerraExplorer_For_Web_Tutorial: "TerraExplorer For Web Tutorial",
    settings_view_tutorial: "Tutorial",
    settings_MGRS_Coordinates: "Show MGRS Coordinates",
    settings_navigation_buttons: "Navigation Controls",
    settings_center_sign: "Center Sign",
    settings_long_press: "Menu Button for Long Press:",
    Edit_Message: "Edit Message",
    Edit_Message_Tool_Title: "Edit Message Tool",
    Message_Type_Text: "Text",
    Message_Type_HtmlImage: "Html/Image",
    Message_Type_Script: "Script",
    Message_Type_Attributes: "Attributes",
    Message_Type: "Type",
    Message_Caption: "Caption",
    Message_Size: "Size",
    Message_Position: "Position",
    Message_TimeToClose: "Close after",
    Message_Text: "Text",
    Position_By_Feature: "From Feature",
    about_registered: "&reg;",
    about_version: "Version:",
    about_skyline_logo: "The Skyline logo and TerraExplorer are trademarks of Skyline Software Systems.",
    about_copyright: "Copyright: &copy; 2019, Skyline Software Systems, Inc. All right reserved.",
    about_patents: "Protected by U.S. Patents: 6111583,6433792,6496189,6704017,7551172,8237713. Other patents pending.",
    about_general_info: "General information:",
    about_general_info_email: "info@skylineglobe.com",
    about_technical_support: "Technical support:",
    about_technical_support_email: "support@skylineglobe.com",
    warning_depth_buffer_picking_not_supported: "TerraExplorer Warning: Picking from the depth buffer is not supported.",
    Underground_tool_UndergroundMode: "Underground Mode",
    Underground_tool_Warrning1: "Your browser does not support 'WEBGL_depth_texture' extension.",
    Underground_tool_Warrning2: "As a result, underground transparency will be disabled.",
    shadow_mode_on: 'Shadow mode is ON',
    shadow_mode_off: 'Shadow mode is OFF',
    Measurement_Header: "Tools",
    TerrainAnalysis_Header: "Modes ",
    Shadow_Header: "Time And Shadow",
    NavigationModes_Header: "Modes",
    NavigationTools_Header: "Tools",
    NavigationPlaces_Header: "Locations and Presentations",
    CPT_No_defaultLocation_Notification: "Point cloud layers that do not have a default location cannot be read by TerraExplorer for Web",
    ERR_layer_not_found: "Layer '${layerName}' not found",
    ERR_layer_not_found_no_name: "Layer not found or the current user has only view permission for this SkylineGlobe Server", 
    ERR_WFSServiceDown: "Service 'Features' is not allowed by the server",
    ERR_WMSServiceDown: "Service 'Maps' is not allowed by the server",
    ERR_3DMLServiceDown: "Service '3D Mesh' is not allowed by the server",
    ERR_CPTServiceDown: "Service 'Point Cloud' is not allowed by the server",
    ERR_NetworkError: "Network error - Try to enable CORS",
    Date: "Date:",
    Hour: "Hour:",
    OK: "OK",
    Load: "Load",
    Unavailable: "Unavailable",
    layer_toolbox_tooltip_select: "Select feature",
    layer_toolbox_tooltip_attributes_table: "Attributes table",
    layer_toolbox_tooltip_delete_layer: "Remove the layer from the project",
    layer_toolbox_tooltip_refresh_layer: "Refresh layer",
    layer_toolbox_tooltip_layer_properties: "Layer properties",
    layer_error_reading_features: 'Failed to retrieve features from server',
    sgAccount_Login: 'Log in',
    sgAccount_LoginTitle: 'SkylineGlobe Login',
    sgAccount_FailedConnectSG: 'failed to connect SG',
    sgAccount_AccountTitle: "SkylineGlobe - My Account",
    OBJECT_WITHOUT_NAME: "Object",
    search_service_is_unavailable: "The search service is currently unavailable.",
    search_service_error: "No search provider is configured for this site.",
    Layers_NotFound: "not found",
    Layers_NotAuthorized: "not authorized",
    Layers_FailToLoad: "failed to load",
    end: ""
});


